# Site settings
title: Rutger Rauws
description: Personal homepage about Rutger Rauws
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rutger Rauws
user_description: "Hi! Welcome on my homepage. My name is Rutger Rauws, and I am a 29-year-old Council Member and Software Engineer living in Eindhoven, The Netherlands.
<br /><br />

I was born and raised in the city of Almelo, The Netherlands. After studying Computer Science at Delft University of Technology for a year I moved to Eindhoven and continued studying Computer Science. During my academic carreer I shifted focus from Windows and .NET to GNU/Linux and languages such as C++. My interest lies in low-level software development and computer graphics.
<br/><br/>

Nowadays I am still an active software engineer, I'm also active as a local council member for the party <a href=\"//eindhoven.groenlinks.nl\">GroenLinks</a>. If you wish to learn more about my political activities, have a look at <a href=\"//eindhoven.groenlinks.nl/onze-mensen/rutger-rauws\">my party's personal page</a> or follow me on social media.

Please find other information about me below. Feel free to contact me using the contact information at the top of the page."

user_title: Software Engineer
email: contact@rutgerrauws.nl
twitter_username: RutgerRauws
facebook_username: RutgerRauws
instagram_username: RutgerRauws
linkedin_username: RutgerRauws
github_username:  RutgerRauws

exclude: ['package.json', 'src' , 'node_modules']
